base_url = "https://new.hegdeatri.com"
compile_sass = true
title = "hegde-atri's theme"
description = "simple yet elegant blog theme"
highlight_code = true
generate_feed = true

taxonomies = [
  {name = "categories", rss = true},
  {name = "tags", rss = true},
]

[extra]
author = "Atri Hegde"
blog_menu = [
  {url = "$BASE_URL", name = "Home"},
  {url = "$BASE_URL/posts", name = "Posts",},
  {url = "$BASE_URL/projects", name = "Projects",},
  {url = "$BASE_URL/categories", name = "Categories",},
  {url = "$BASE_URL/tags", name = "Tags",},
  {url = "$BASE_URL/about", name = "About",},
]
comments = true