# The URL the site will be built for
base_url = "https://new.hegdeatri.com"

compile_sass = true
title = "Atri Hegde"
description = "Personal blog and projects page"
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
author = "Atri Hegde"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/posts", name = "Posts"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/projects", name = "Projects"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Atri Hegde"
