base_url = "https://new.hegdeatri.com"
compile_sass = true
build_search_index = false

taxomonies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[extra]
author = "Atri Hegde"
comments = true
