base_url = "https://new.hegdeatri.com"
compile_sass = true
build_search_index = true
theme = "hegde-atri"
title = "Atri Hegde"
description = "A personal blog theme"
output_dir = "public"
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
  { name = "categories", feed = true},
  { name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[extra]
author = "Atri Hegde"
comments = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"



[extra.social]
github = "hegde-atri"
gitlab = "hegde-atri"